// tslint:disable
/**
 * win-monitor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MainMonitorModel
 */
export interface MainMonitorModel {
    /**
     * 开机时间
     * @type {number}
     * @memberof MainMonitorModel
     */
    boot_time?: number;
    /**
     * 空闲
     * @type {number}
     * @memberof MainMonitorModel
     */
    free?: number;
    /**
     * 主机唯一标识
     * @type {string}
     * @memberof MainMonitorModel
     */
    host_id?: string;
    /**
     *
     * @type {number}
     * @memberof MainMonitorModel
     */
    id?: number;
    /**
     * 名称
     * @type {string}
     * @memberof MainMonitorModel
     */
    name?: string;
    /**
     * 使用率
     * @type {number}
     * @memberof MainMonitorModel
     */
    per?: number;
    /**
     * 监控时间
     * @type {number}
     * @memberof MainMonitorModel
     */
    time?: number;
    /**
     * 总量
     * @type {number}
     * @memberof MainMonitorModel
     */
    total?: number;
    /**
     * 监控类型 cpu/mem/disk/open
     * @type {string}
     * @memberof MainMonitorModel
     */
    type?: string;
    /**
     * 单位
     * @type {string}
     * @memberof MainMonitorModel
     */
    unit?: string;
    /**
     * 已使用
     * @type {number}
     * @memberof MainMonitorModel
     */
    used?: number;
}


