// tslint:disable
/**
 * win-monitor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {MainHostScreenshot} from './main-host-screenshot';
import {MainMonitorModel} from './main-monitor-model';

/**
 *
 * @export
 * @interface MainHostMonitor
 */
export interface MainHostMonitor {
    /**
     *
     * @type {Array<MainMonitorModel>}
     * @memberof MainHostMonitor
     */
    monitors?: Array<MainMonitorModel>;
    /**
     *
     * @type {MainHostScreenshot}
     * @memberof MainHostMonitor
     */
    screenshot?: MainHostScreenshot;
}


