// tslint:disable
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MainHelloReq
 */
export interface MainHelloReq {
    /**
     * 名称
     * @type {string}
     * @memberof MainHelloReq
     */
    name: MainHelloReqNameEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum MainHelloReqNameEnum {
    Tom = 'tom',
    Jerry = 'jerry'
}



