// tslint:disable
/**
 * win-monitor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MainMonitorConf
 */
export interface MainMonitorConf {
    /**
     * 监控数据最大保存数量
     * @type {number}
     * @memberof MainMonitorConf
     */
    maxMonitorSize?: number;
    /**
     * 采集间隔时间
     * @type {number}
     * @memberof MainMonitorConf
     */
    monitorCollectInterval?: number;
    /**
     * 监控开关
     * @type {boolean}
     * @memberof MainMonitorConf
     */
    monitorEnable?: boolean;
    /**
     * 监控上传间隔时间
     * @type {number}
     * @memberof MainMonitorConf
     */
    monitorUploadInterval?: number;
    /**
     * 截图开关
     * @type {boolean}
     * @memberof MainMonitorConf
     */
    screenshotEnable?: boolean;
    /**
     * 截图间隔时间
     * @type {number}
     * @memberof MainMonitorConf
     */
    screenshotIntervalTime?: number;
    /**
     * 多少张截图后强制上传
     * @type {number}
     * @memberof MainMonitorConf
     */
    screenshotUploadIntervalCount?: number;
    /**
     * 当前截图和上次截图对比，如果相似度小于该值则上传
     * @type {number}
     * @memberof MainMonitorConf
     */
    screenshotUploadMinDistance?: number;
    /**
     * 是否上传原图
     * @type {boolean}
     * @memberof MainMonitorConf
     */
    screenshotUploadOriginImage?: boolean;
}


