// tslint:disable
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MainHelloResp
 */
export interface MainHelloResp {
    /**
     * 年龄
     * @type {number}
     * @memberof MainHelloResp
     */
    age?: number;
    /**
     * 名称
     * @type {string}
     * @memberof MainHelloResp
     */
    name?: string;
}


