// tslint:disable
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MainResponse
 */
export interface MainResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof MainResponse
     */
    code?: number;
    /**
     *
     * @type {string}
     * @memberof MainResponse
     */
    data?: string;
    /**
     * 状态描述
     * @type {string}
     * @memberof MainResponse
     */
    msg?: string;
}


