// tslint:disable
/**
 * win-monitor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MainHostScreenshot
 */
export interface MainHostScreenshot {
    /**
     * 截图时间
     * @type {number}
     * @memberof MainHostScreenshot
     */
    captureTime?: number;
    /**
     * 当前截图
     * @type {string}
     * @memberof MainHostScreenshot
     */
    cur?: string;
    /**
     * 相似度
     * @type {number}
     * @memberof MainHostScreenshot
     */
    distance?: number;
    /**
     * 主机唯一标识
     * @type {string}
     * @memberof MainHostScreenshot
     */
    host_id?: string;
    /**
     *
     * @type {number}
     * @memberof MainHostScreenshot
     */
    id?: number;
    /**
     * 上次截图
     * @type {string}
     * @memberof MainHostScreenshot
     */
    pre?: string;
}


