// tslint:disable
/**
 * win-monitor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 * @interface MainHost
 */
export interface MainHost {
    /**
     * ex: uuid
     * @type {string}
     * @memberof MainHost
     */
    hostID?: string;
    /**
     *
     * @type {string}
     * @memberof MainHost
     */
    hostname?: string;
    /**
     * ex: freebsd, linux
     * @type {string}
     * @memberof MainHost
     */
    os?: string;
    /**
     * ex: ubuntu, linuxmint
     * @type {string}
     * @memberof MainHost
     */
    platform?: string;
    /**
     * ex: debian, rhel
     * @type {string}
     * @memberof MainHost
     */
    platformFamily?: string;
    /**
     * version of the complete OS
     * @type {string}
     * @memberof MainHost
     */
    platformVersion?: string;
}


