// tslint:disable
/**
 * win-monitor
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {MainMonitorItem} from './main-monitor-item';

/**
 * 
 * @export
 * @interface MainMonitor
 */
export interface MainMonitor {
    /**
     * 主机唯一标识
     * @type {string}
     * @memberof MainMonitor
     */
    hostId?: string;
    /**
     * 监控数据
     * @type {Array<MainMonitorItem>}
     * @memberof MainMonitor
     */
    items?: Array<MainMonitorItem>;
}


