// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/client/monitor": {
            "post": {
                "description": "监控数据上传",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户端接口"
                ],
                "summary": "监控数据上传",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "参数",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Monitor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/client/register": {
            "post": {
                "description": "设备注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户端接口"
                ],
                "summary": "设备注册",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "参数",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Host"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/main.MonitorConf"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/client/screenshot": {
            "post": {
                "description": "设备注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户端接口"
                ],
                "summary": "截图上传",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "参数",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.HostScreenshot"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/console/host": {
            "get": {
                "description": "主机列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制台接口"
                ],
                "summary": "主机列表",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/main.HostModel"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/console/host/:hostId": {
            "get": {
                "description": "监控数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制台接口"
                ],
                "summary": "监控数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "参数",
                        "name": "hostId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/main.HostMonitor"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/console/host/conf": {
            "post": {
                "description": "程序主机配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "控制台接口"
                ],
                "summary": "程序主机配置",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "参数",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.HostModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Host": {
            "type": "object",
            "properties": {
                "hostID": {
                    "description": "ex: uuid",
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "os": {
                    "description": "ex: freebsd, linux",
                    "type": "string"
                },
                "platform": {
                    "description": "ex: ubuntu, linuxmint",
                    "type": "string"
                },
                "platformFamily": {
                    "description": "ex: debian, rhel",
                    "type": "string"
                },
                "platformVersion": {
                    "description": "version of the complete OS",
                    "type": "string"
                }
            }
        },
        "main.HostModel": {
            "type": "object",
            "required": [
                "config",
                "hostID"
            ],
            "properties": {
                "OS": {
                    "description": "系统",
                    "type": "string"
                },
                "config": {
                    "description": "配置信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/main.MonitorConf"
                        }
                    ]
                },
                "customName": {
                    "description": "自定义主机名",
                    "type": "string"
                },
                "firstRegisterTime": {
                    "description": "首次注册时间",
                    "type": "integer"
                },
                "hostID": {
                    "description": "主机唯一标识",
                    "type": "string"
                },
                "hostname": {
                    "description": "主机名",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notifyPush": {
                    "description": "是否推送告警",
                    "type": "boolean"
                },
                "platform": {
                    "description": "系统平台",
                    "type": "string"
                },
                "platformFamily": {
                    "description": "系统家族",
                    "type": "string"
                },
                "platformVersion": {
                    "description": "系统版本",
                    "type": "string"
                }
            }
        },
        "main.HostMonitor": {
            "type": "object",
            "properties": {
                "monitors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.MonitorModel"
                    }
                },
                "screenshot": {
                    "$ref": "#/definitions/main.HostScreenshot"
                }
            }
        },
        "main.HostScreenshot": {
            "type": "object",
            "properties": {
                "captureTime": {
                    "description": "截图时间",
                    "type": "integer"
                },
                "cur": {
                    "description": "当前截图",
                    "type": "string"
                },
                "distance": {
                    "description": "相似度",
                    "type": "integer"
                },
                "host_id": {
                    "description": "主机唯一标识",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pre": {
                    "description": "上次截图",
                    "type": "string"
                }
            }
        },
        "main.Monitor": {
            "type": "object",
            "properties": {
                "hostId": {
                    "description": "主机唯一标识",
                    "type": "string"
                },
                "items": {
                    "description": "监控数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.MonitorItem"
                    }
                }
            }
        },
        "main.MonitorConf": {
            "type": "object",
            "properties": {
                "maxMonitorSize": {
                    "description": "监控数据最大保存数量",
                    "type": "integer"
                },
                "monitorCollectInterval": {
                    "description": "采集间隔时间",
                    "type": "integer"
                },
                "monitorEnable": {
                    "description": "监控开关",
                    "type": "boolean"
                },
                "monitorUploadInterval": {
                    "description": "监控上传间隔时间",
                    "type": "integer"
                },
                "screenshotEnable": {
                    "description": "截图开关",
                    "type": "boolean"
                },
                "screenshotIntervalTime": {
                    "description": "截图间隔时间",
                    "type": "integer"
                },
                "screenshotUploadIntervalCount": {
                    "description": "多少张截图后强制上传",
                    "type": "integer"
                },
                "screenshotUploadMinDistance": {
                    "description": "当前截图和上次截图对比，如果相似度小于该值则上传",
                    "type": "integer"
                },
                "screenshotUploadOriginImage": {
                    "description": "是否上传原图",
                    "type": "boolean"
                }
            }
        },
        "main.MonitorItem": {
            "type": "object",
            "properties": {
                "bootTime": {
                    "description": "开机时间",
                    "type": "integer"
                },
                "free": {
                    "description": "空闲",
                    "type": "number"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "per": {
                    "description": "使用率",
                    "type": "number"
                },
                "time": {
                    "description": "监控时间",
                    "type": "integer"
                },
                "total": {
                    "description": "总量",
                    "type": "number"
                },
                "type": {
                    "description": "cpu/mem/disk/open",
                    "type": "string"
                },
                "unit": {
                    "description": "单位",
                    "type": "string"
                },
                "used": {
                    "description": "已使用",
                    "type": "number"
                }
            }
        },
        "main.MonitorModel": {
            "type": "object",
            "properties": {
                "boot_time": {
                    "description": "开机时间",
                    "type": "integer"
                },
                "free": {
                    "description": "空闲",
                    "type": "number"
                },
                "host_id": {
                    "description": "主机唯一标识",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "per": {
                    "description": "使用率",
                    "type": "number"
                },
                "time": {
                    "description": "监控时间",
                    "type": "integer"
                },
                "total": {
                    "description": "总量",
                    "type": "number"
                },
                "type": {
                    "description": "监控类型 cpu/mem/disk/open",
                    "type": "string"
                },
                "unit": {
                    "description": "单位",
                    "type": "string"
                },
                "used": {
                    "description": "已使用",
                    "type": "number"
                }
            }
        },
        "main.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
